### ISSUE TITLE
SRD Parser

### ISSUE THREAD

**Issue by lennycolton** [VFPC/VFPC#53]
Support for new features added by the SRD Parser:

- [x] API Calls
    - [x] VFPC/UKVFPCAPI#24
    - [x] Calls should refer only to requested airports, blanket requests for the entire DB to be removed.
- [x] SID-Less Routes
    - [x] Lack of SID to be removed as an automatic failure reason.
    - [x] Non-SID routes to be supported, where the SID point is entered as `""`.
    - [x] SID-only airports to reject non-SID routes as having an invalid SID.
    - [x] Where alternative SIDs are suggested, `No SID` shall be used to indicate valid non-SID routes exist.
    - [x] Runway-specific SIDs to be rejected (not treated as `No SID`) when wrong runway config in use.
- [x] Banned Restrictions
    - [x] `banned` flag - Reject SID/constraint and display `alt` data as with normal failure.
        - [x] VFPC/SRDParser#1
- [x] SID-Level vs Constraint-Level Restrictions
    - [x] Move the restriction checks into a separate function.
    - [x] An aircraft must pass at least 1 SID-level (if any present) and at least 1 constraint-level (if any present) restriction.
    - [x] `override` flag to be removed.
    - [x] `sidlevel` flag - Treat a specific restriction as SID-level, even when it is present in a constraint-level restrictions array.
        - [x] VFPC/SRDParser#1
    - ~~Distinguish between SID-Level and Constraint-Level restrictions in output.~~ **Pushed Back to v3.6**
- [x] Alerts
    - [x] `warn` flag - Change colour of departure list item to yellow, otherwise treat as though it has passed as normal.
    - [x] `ban` flag - Change colour of departure list item to red, change departure list item from `OK!` to `BAN`.
    - [x] Add output function for warnings/ban reasons.
- [x] VFPC/UKVFPCAPI#25
    - This section to be handled at API-level. No plugin changes required.

**Comment by tjmills-dev** [comment]
Is there a method of dismissing a VFPC complaint? Just thinking of intentionally non-standard departures

**Comment by lennycolton** [comment]
> 
> 
> Is there a method of dismissing a VFPC complaint? Just thinking of intentionally non-standard departures

~~I feel like this would need some kind of addition to the flight plan. Methods involving the callsign or CID may get messy and TAG IDs don't directly relate to flight plans (rather the radar blip, which can then be associated to a flight plan - this is not always done correctly in C/S modes).~~

~~Open to ideas surrounding implementation.~~ #59

**Comment by lennycolton** [comment]
~~I've had a think - I'm gonna try associating some parameter to an aircraft's tag (but not use the tag ID, which is attached to the radar blip), which should avoid entering it directly into the flight plan but preserve association to it.~~ #59

**Comment by lennycolton** [comment]
#17 merged into this issue.
